language: node_js

node_js:
 - lts/*

addons:
  chrome: stable

cache:
  paths:
    - node_modules/

before_script:
 - npm install -g firebase-tools

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export CHROME_BIN=/usr/bin/google-chrome

script:
  - ng build --aot --prod

branches:
 only:
  - master

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --token $FIREBASE_TOKEN
  on:
    branch: master
